# Generated by Django 4.0.4 on 2022-04-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_uploadimage_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='imageURL',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='uploader',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
